/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        ConversorMoneda conversor = new ConversorMoneda();

        int opcion = 0;
        String monedaOrigen = "";
        String monedaDestino = "";
        double cantidad = 0;
        double resultado = 0;
        ArrayList<Moneda> monedas = getListMonedas();
        Scanner sc = new Scanner(System.in);

        while (true) {
            try {
                printMonedas(monedas);
                System.out.println("Ingrese Moneda de origen");
                opcion = sc.nextInt();
                if (opcion == 0) {
                    break;
                }
                monedaOrigen = monedas.get(opcion - 1).getBase_code();

                printMonedas(monedas);
                System.out.println("Ingrese Moneda de destino");
                opcion = sc.nextInt();
                if (opcion == 0) {
                    break;
                }

                monedaDestino = monedas.get(opcion - 1).getBase_code();

                System.out.println("--------------------------------------------");
                System.out.println("Ingrese Cantidad a convertir");
                cantidad = sc.nextDouble();
                sc.nextLine(); // <-- limpia el buffer

                System.out.println("--------------------------------------------");
                System.out.println("RESULTADO: ");
                resultado = conversor.convertir(monedaOrigen, monedaDestino, cantidad);
                System.out.println(
                        cantidad + " " + monedaOrigen + " " + "equivale a " + resultado + " " + monedaDestino + "");
            } catch (IndexOutOfBoundsException e) {
                System.out.println("Error: No existe esa moneda en la lista.");

            } catch (InputMismatchException e) {
                System.out.println("Error: Debes ingresar un número entero válido.");
                sc.nextLine();
            } catch (RuntimeException e) {
                System.out.println(e.getMessage());
                System.out.println("Finalizando la aplicación.");
            }
            catch (Exception e) {
                System.out.println("Ocurrio un error");
                System.out.println(e.getMessage());
                break;
            }

        }
        sc.close();

    }

    public static ArrayList<Moneda> getListMonedas() {
        ArrayList<Moneda> monedas = new ArrayList<>();
        monedas.add(new Moneda("USD", "Dólar Estadounidense"));
        monedas.add(new Moneda("EUR", "Euro"));
        monedas.add(new Moneda("GBP", "Libra Esterlina"));
        monedas.add(new Moneda("JPY", "Yen Japonés"));
        monedas.add(new Moneda("CHF", "Franco Suizo"));
        monedas.add(new Moneda("BOB", "Boliviano"));
        monedas.add(new Moneda("PEN", "Sol Peruano"));
        monedas.add(new Moneda("ARS", "Peso Argentino"));
        monedas.add(new Moneda("MXN", "Peso Mexicano"));
        monedas.add(new Moneda("BRL", "Real Brasileño"));

        return monedas;
    }

    public static void printMonedas(ArrayList<Moneda> monedas) {
        System.out.println("--------------------------------------------");
        int i = 1;
        for (Moneda moneda : monedas) {
            System.out.println(i + ". " + moneda.getBase_code() + "->" + moneda.getName_currency());
            i++;
        }
        System.out.println("0. SALIR");
        System.out.println("--------------------------------------------");
    }

}
